"""Shared runtime settings for the k8s-dynamic-allocator deployment."""

DEFAULT_NAMESPACE = "swlabpods"

REDIS_URL = "redis://controller-queue-redis:6379/0"
CONTROLLER_SERVICE_HOST = "controller-service"
CONTROLLER_SERVICE_PORT = 9001
CONTROLLER_RELEASE_PATH = "/api/compute/release/"
CONTROLLER_RELEASE_TIMEOUT_SECONDS = 10
WAIT_QUEUE_PREFIX = "kda:waitq"
DEFAULT_COMPUTE_TYPE = "general"
CONTROLLER_LEASE_NAME = "controller-leader"
LEASE_DURATION_SECONDS = 15
LEASE_RENEW_INTERVAL_SECONDS = 5
LEASE_RETRY_INTERVAL_SECONDS = 2

WAIT_QUEUE_TIMEOUT_SECONDS = 1800
WAIT_QUEUE_TICKET_TTL_SECONDS = 7200
WAIT_QUEUE_LOCK_TTL_SECONDS = 60
WAIT_QUEUE_ALLOCATING_TTL_SECONDS = 60
ASSIGNED_CONTEXT_TTL_SECONDS = 2592000
COMPUTE_AVAILABLE_TTL_SECONDS = 600
WAIT_QUEUE_MAX_RETRIES = 3
WAIT_QUEUE_WORKER_INTERVAL_SECONDS = 1.0
WAIT_QUEUE_COMPUTE_REFRESH_SECONDS = 15.0
WAIT_QUEUE_BATCH_LIMIT = 10
WAIT_QUEUE_MOUNT_CONCURRENCY = 10

COMPUTE_AVAILABILITY_WATCH_ENABLED = True
COMPUTE_AVAILABILITY_WATCH_TIMEOUT_SECONDS = 60
COMPUTE_AVAILABILITY_WATCH_RETRY_SECONDS = 1.0

COMPUTE_AGENT_TIMEOUT_SECONDS = 30.0
COMPUTE_AGENT_MOUNT_TIMEOUT_SECONDS = 30.0
COMPUTE_AGENT_UNMOUNT_TIMEOUT_SECONDS = 30.0
COMPUTE_AGENT_HTTP_PORT = 8080
COMPUTE_AGENT_PORT = COMPUTE_AGENT_HTTP_PORT
COMPUTE_AGENT_TCP_PORT = 8081
COMPUTE_AGENT_RELEASE_NOTIFY_DEBOUNCE_SECONDS = 10

TCP_KEEPIDLE = 10
TCP_KEEPINTVL = 5
TCP_KEEPCNT = 3

LOG_FORMAT = "detailed"
APP_LOG_LEVEL = "INFO"

try:
    c
except NameError:
    c = None

if c is not None:
    from kubessh.authentication.dummy import DummyAuthenticator

    c.KubeSSH.host_key_path = "./kubessh/dummy-kubessh-host-key"
    c.KubeSSH.debug = False
    c.KubeSSH.authenticator_class = DummyAuthenticator
    c.KubeSSH.default_namespace = DEFAULT_NAMESPACE
