apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: kda-test

images:
  - name: harbor.cu.ac.kr/k8s_dynamic_allocator/controller
    newTag: latest
  - name: harbor.cu.ac.kr/k8s_dynamic_allocator/swlabssh
    newTag: latest

patches:
  - path: patch_controller_env.yaml
  - path: patch_swlabssh_env.yaml
  - path: patch_redis_storage.yaml
  - path: patch_logging_storage.yaml
  - path: patch_fluent_bit_env.yaml
