apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: swlabpods
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  # storageClassName: normal-r3        # main server
  storageClassName: openebs-rwx    # test server
