apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kda-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller-sa
      containers:
      - name: controller
        image: harbor.cu.ac.kr/k8s_dynamic_allocator/controller:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        env:
        - name: REDIS_URL
          value: redis://controller-queue-redis:6379/0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: kda-test
spec:
  selector:
    app: controller
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
  type: ClusterIP
