apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swlabpods

resources:
  - 00-rbac.yaml
  - 10-pvc.yaml
  - 30-daemonset.yaml
  - 40-cronjob-rotate.yaml

configMapGenerator:
  - name: fluent-bit-config
    files:
      - fluent-bit.conf
      - parsers.conf
    options:
      labels:
        k8s-dynamic-allocator/deploy-stage: logging
